include:
  - project: 'ktrust/kbrain-solution/devops-shared'
    file: '/.gitlab-ci.yml'
    ref: main

image: docker:latest

services:
  - docker:dind

stages:
  - trigger_scans
  - lint
  - test
  - build

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: "overlay2"
  GO_VERSION: "1.22"
  PLUGIN_NAME: "connectionbalancer"
  GOPATH: "$CI_PROJECT_DIR/.go"
  GOMODCACHE: "$CI_PROJECT_DIR/.go/pkg/mod"

cache:
  key: 
    files:
      - go.sum
  paths:
    - .go/pkg/mod
    - .cache/go-build
  policy: pull-push

lint:
  stage: lint
  image: golangci/golangci-lint:latest
  before_script:
    - go mod tidy
    - go mod vendor
  script:
    - golangci-lint run -v --timeout=10m --modules-download-mode=vendor
  allow_failure: true

unit_tests:
  stage: test
  image: golang:$GO_VERSION
  before_script:
    - go mod tidy
    - go mod download
  script:
    - go test -v ./...

build_and_push:
  stage: build
  image: docker:latest
  before_script:
    - apk add --no-cache docker-cli docker-cli-compose git
    - docker version
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker buildx create --use
  script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx inspect --bootstrap
    - >
      docker buildx build
      --platform linux/amd64,linux/arm64
      --cache-from=type=registry,ref=$CI_REGISTRY_IMAGE:cache
      --cache-to=type=registry,ref=$CI_REGISTRY_IMAGE:cache,mode=max
      --push
      -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
      -t $CI_REGISTRY_IMAGE:latest .
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual